Repository cloudfoundry/bosh-bootloader, pull requests merged in 2018-10, with the labels that each got.

#382 Remove unnecessary http_proxy env var
  docs/credhub.md
Labels: scheduled

#368 Remove static IP that comes from nowhere
  plan-patches/cfcr-vsphere/cloud-config/cfcr-overrides.yml
Labels: scheduled

#370 plan-patch cfcr-vsphere - fixes url for vsphere xenial stemcell
  plan-patches/cfcr-vsphere/README.md
Labels: unscheduled

#372 Allow user to specify dns managed zone
  plan-patches/cfcr-gcp/terraform/cfcr_dns_override.tf
Labels: in progress

#381 add patch to deploy cfcr on Azure.
  plan-patches/cfcr-azure/README.md
  plan-patches/cfcr-azure/cloud-config/better-compiler.yml
  plan-patches/cfcr-azure/cloud-config/cfcr-cloud-config-ops.yml
  plan-patches/cfcr-azure/cloud-config/cfcr-subnet-ops.yml
  plan-patches/cfcr-azure/create-director-override.sh
  plan-patches/cfcr-azure/create-jumpbox-override.sh
  plan-patches/cfcr-azure/ops/cfcr-vm-extensions.yml
  plan-patches/cfcr-azure/ops/cloud-provider.yml
  plan-patches/cfcr-azure/ops/jumpbox-use-managed-disk.yml
  plan-patches/cfcr-azure/ops/single-master.yml
  plan-patches/cfcr-azure/ops/single-worker.yml
  plan-patches/cfcr-azure/ops/small-vm.yml
  plan-patches/cfcr-azure/ops/use-cfcr-subnet.yml
  plan-patches/cfcr-azure/ops/use-latest-kubo-release.yml
  plan-patches/cfcr-azure/ops/use-vm-extensions.yml
  plan-patches/cfcr-azure/terraform/cfcr_lb_override.tf
  plan-patches/cfcr-azure/terraform/cfcr_outputs_override.tf
  plan-patches/cfcr-azure/terraform/cfcr_resource_group_override.tf
  plan-patches/cfcr-azure/terraform/cfcr_sg_override.tf
  plan-patches/cfcr-azure/terraform/cfcr_subnet.tf
Labels: in progress

#389 switch to use the official repo, because pr for azure kubo merged.
  plan-patches/README.md
  plan-patches/cfcr-azure/README.md
Labels: unscheduled

#392 should use managed disk ops file when destroying bbl if create bbl is using it.
  plan-patches/cf-azure/delete-director-override.sh
  plan-patches/cf-azure/delete-jumpbox-override.sh
  plan-patches/cf-lite-azure/delete-director-override.sh
  plan-patches/cf-lite-azure/delete-jumpbox-override.sh
  plan-patches/cfcr-azure/delete-director-override.sh
  plan-patches/cfcr-azure/delete-jumpbox-override.sh
Labels: scheduled
